export type MdfErrorCode =
	| "CONFIG_NOT_FOUND"
	| "CONFIG_ALREADY_EXISTS"
	| "SCHEMA_VALIDATION"
	| "INVALID_FRONT_MATTER"
	| "INVALID_FILE_NAME"
	| "INVALID_CONTENT"
	| "FILE_EXISTS"
	| "FRONT_MATTER_NOT_FOUND"
	| "FRONT_MATTER_PARSE"
	| "NO_MATCHING_FILES"
	| "INVALID_FILTER_EXPRESSION"
	| "INVALID_QUERY_FILTER"
	| "TEMPLATE_NOT_FOUND"
	| "INVALID_UPDATE_INPUT"
	| "DEFAULT_VALUE_UNAVAILABLE"
	| "VIRTUAL_PATH_NOT_CONFIGURED"
	| "INVALID_VIRTUAL_PATH_VALUE"
	| "INVALID_VIRTUAL_SLUG_VALUE"
	| "ALIAS_NOT_FOUND"
	| "ALIAS_CYCLE"
	| "INVALID_ALIAS_COMMAND"
	| "VIEWER_NO_DOCUMENTS"
	| "INVALID_VIEWER_PORT"
	| "VIEWER_DUPLICATE_SLUG"
	| "VIEWER_ASSETS_MISSING"
	| "VIEWER_ASSETS_NOT_BUILT"
	| "APPEND_INVALID_INPUT"
	| "APPEND_NOTE_NOT_FOUND"
	| "APPEND_SOURCE_NOT_FOUND"
	| "APPEND_FILE_CONFLICT"
	| "INVALID_EXPORT_OPTIONS";

export class MdfError extends Error {
	constructor(
		public readonly code: MdfErrorCode,
		message: string,
	) {
		super(message);
		this.name = "MdfError";
	}
}
